return {
  Array = " []  ",
  Boolean = " ◩  ",
  Class = "   ",
  Color = "   ",
  Constant = "   ",
  Constructor = "   ",
  Enum = "   ",
  EnumMember = "   ",
  Event = "   ",
  Field = " ﰠ  ",
  File = "   ",
  Folder = "   ",
  Function = "   ",
  Interface = "ﰮ  ",
  Key = "   ",
  Keyword = "   ",
  Method = "   ",
  Module = " {} ",
  Namespace = "   ",
  Null = " ﳠ  ",
  Number = "   ",
  Object = " {}  ",
  Operator = "   ",
  Package = "   ",
  Property = "   ",
  Reference = "   ",
  Snippet = "   ",
  String = "   ",
  Struct = "   ",
  Text = "   ",
  TypeParameter = "   ",
  Unit = " 塞 ",
  Value = "   ",
  Variable = "   "
}

